### ISSUE TITLE
Implement window 5-mer as a bitfield in a `u8`

### ISSUE THREAD

**Issue by jakobnissen** [wwood/smafa#46]
I believe smafa's distance computation might be able to become significantly faster if each nucleotide is represented as a `u8`, where one of the lower 5 bits are set, instead of a `[bool; 5]`. The distance computation could then be done using an xor and a population count instruction, which will vectorize nicely.
A little more tricky, but even more efficient, would be to pack it into 4 bits per symbol, allowing 2 symbols per byte. However, that would change the distance computation where I'm not sure what the ideal is.

However, this would change the smafa database format.

I'm willing to give it a go if you're interested.

**Comment by wwood** [comment]
Hey,

Of course you are welcome to give it a go, but at the moment they are represented not as a series of `[bool; 5]` but actually as a concatenation of them e.g. for a 60bp sequence it is a `[bool; 5*60]` array, at least when querying.

My understanding is that is is already using the parallel xor instructions. I actually even looked at the assembly instructions and came away with the conclusion that the majority of the time was spent in parallel xor type instructions (from memory).

**Comment by jakobnissen** [comment]
I'll give it a try for fun. I would assume that improving the "coding density" by 5x would make it faster simply by requring 5x fewer xor instructions.
One question: The Ns are not treated specially with computing distances, e.g. two positions having Ns are considered identical and has a distance of zero even if we don't know that the true underlying DNA is the same.
Is this on purpose?
